# MIUI ADD: Power_PowerSaveModeV2
obj-$(CONFIG_MI_POWER_SAVE) += powersave.o
powersave-$(CONFIG_MI_POWER_SAVE) += powersave_main.o
powersave-$(CONFIG_MI_POWER_SAVE) += soc_policy_control.o
# END Power_PowerSaveModeV2
