






# MIUI ADD: Power_UnionPowerCore
obj-y                                   += unionpower/
# END Power_UnionPowerCore

# MIUI ADD: Power_PowerSaveModeV2
obj-y                                   += powersave/
# END Power_PowerSaveModeV2
